# From: https://hk.saowen.com/a/39274e1bbfd2807384ce737dba9bce140f42685a1b3e1badf16b22ce84584caf
# 注意這裏的vertion是docker-compose yaml格式的version 不同的version支持不同的語法
version: '2'

# 定義服務 我這裏nginx + php
services:

 nginx:
  # 依賴關係 先跑php
  depends_on:
   - "php"

  image: "nginx:latest"

  # 數據卷
  volumes:
   - "$PWD/conf.d:/etc/nginx/conf.d"
   - "$PWD/html:/usr/share/nginx/html"

  # 端口映射
  ports:
   - "8080:80"

  # 容器名稱
  container_name: "compose-nginx"

 php:
  image: "php:fpm"
  volumes:
   - "$PWD/html:/var/www/html"
  container_name: "compose-php"
